import type { Metadata } from "next";
import {  Poppins , Bebas_Neue
 , Ubuntu} from "next/font/google";
import "./globals.css";


import {SessionProvider} from "next-auth/react"
import { Toaster } from 'sonner';
import { auth } from "@/auth";
const fontPoppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight:['700']
})
const fontBebasNeue = Bebas_Neue({
  variable: "--font-bebasneue",
  subsets: ["latin"],
  weight:['400']
})

const fontUbuntu = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  weight:['300' , '400' ,'500']
})

export const metadata: Metadata = {
  title: "ShearTime",
  description: "Generated by create next app",
  icons:{
    icon:'/icons/logo-dark.svg',
  }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <SessionProvider session={session}>
      <body
        className={`${fontUbuntu.className} antialiased`}
      >
        
        {children}
        <Toaster position="top-center" />
      </body>
      </SessionProvider>
    </html>
  );
}
